name: Auto Git Tag
author: Ellie Kerns <epkerns@gmail.com>
description: Automatically tag releases based on commit messages
inputs:
  github_token:
    description: GitHub token for authentication
    required: true
  release_branch:
    description: 'The branch to consider as the release branch (default: release)'
    required: false
    default: release
  dry_run:
    description: >-
      Will create the tag without pushing to git, and will still return the tag
      as an output
    required: false
    default: false
outputs:
  PREVIOUS_TAG:
    description: the previous tag
  NEXT_TAG:
    description: ouputed tag
permissions:
  contents: write
runs:
  using: node20
  main: dist/index.js
branding:
  icon: tag
  color: purple
