
name: Custom Auto Tag

on:
  workflow_dispatch:
  push:
    branches: ["*"]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
        - 22
    steps: 
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install deps and build
      run: npm ci && npm run build
    - name: Commit and Push Build
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add dist/index.js
        git commit -m "chore: update dist output"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: AutoTag
      id: tag
      uses: ./
      with:
         release_branch: 'main'       
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.NEXT_TAG }}

    - uses: JasonEtco/build-and-tag-action@v2
      with:
        tag_name: ${{ steps.tag.outputs.NEXT_TAG }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
