
name: Custom Auto Tag

on:
  workflow_dispatch:
  push:
    branches: ["*"]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
        - 22
    steps: 
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: AutoTag
      id: tag
      uses: ./
      with:
         release_branch: 'main'       
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.NEXT_TAG }}
